
LOCAL_PATH := $(call my-dir)

# Install Superuser
include $(CLEAR_VARS)
LOCAL_MODULE := Superuser
LOCAL_SRC_FILES := Superuser.apk
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_PATH  := $(TARGET_OUT_APPS)
LOCAL_MODULE_TAGS := optional
include $(BUILD_PREBUILT)

